  library(tidyverse)

  setwd("/Users/bapu/Documents/work/commissions/harvard/fisheries/bangladesh/")


  
  
  #### Download age-sex specific food consumed files----
  download.file("https://dataverse.harvard.edu/api/access/datafile/2781794", "./nutrition/aux/genus/foodAgeSex/EdibleFood_2011_age0-4_bothsexes.csv")
  download.file("https://dataverse.harvard.edu/api/access/datafile/2776419", "./nutrition/aux/genus/foodAgeSex/EdibleFood_2011_age10-14_female.csv")
  download.file("https://dataverse.harvard.edu/api/access/datafile/2776420", "./nutrition/aux/genus/foodAgeSex/EdibleFood_2011_age10-14_male.csv")
  download.file("https://dataverse.harvard.edu/api/access/datafile/2776422", "./nutrition/aux/genus/foodAgeSex/EdibleFood_2011_age15-19_female.csv")
  download.file("https://dataverse.harvard.edu/api/access/datafile/2776423", "./nutrition/aux/genus/foodAgeSex/EdibleFood_2011_age15-19_male.csv")
  download.file("https://dataverse.harvard.edu/api/access/datafile/2776425", "./nutrition/aux/genus/foodAgeSex/EdibleFood_2011_age20-24_female.csv")
  download.file("https://dataverse.harvard.edu/api/access/datafile/2776424", "./nutrition/aux/genus/foodAgeSex/EdibleFood_2011_age20-24_male.csv")
  download.file("https://dataverse.harvard.edu/api/access/datafile/2776430", "./nutrition/aux/genus/foodAgeSex/EdibleFood_2011_age25-29_female.csv")
  download.file("https://dataverse.harvard.edu/api/access/datafile/2776426", "./nutrition/aux/genus/foodAgeSex/EdibleFood_2011_age25-29_male.csv")
  download.file("https://dataverse.harvard.edu/api/access/datafile/2776427", "./nutrition/aux/genus/foodAgeSex/EdibleFood_2011_age30-34_female.csv")
  download.file("https://dataverse.harvard.edu/api/access/datafile/2776428", "./nutrition/aux/genus/foodAgeSex/EdibleFood_2011_age30-34_male.csv")
  download.file("https://dataverse.harvard.edu/api/access/datafile/2776429", "./nutrition/aux/genus/foodAgeSex/EdibleFood_2011_age35-39_female.csv")
  download.file("https://dataverse.harvard.edu/api/access/datafile/2776432", "./nutrition/aux/genus/foodAgeSex/EdibleFood_2011_age35-39_male.csv")
  download.file("https://dataverse.harvard.edu/api/access/datafile/2776431", "./nutrition/aux/genus/foodAgeSex/EdibleFood_2011_age40-44_female.csv")
  download.file("https://dataverse.harvard.edu/api/access/datafile/2776434", "./nutrition/aux/genus/foodAgeSex/EdibleFood_2011_age40-44_male.csv")
  download.file("https://dataverse.harvard.edu/api/access/datafile/2776435", "./nutrition/aux/genus/foodAgeSex/EdibleFood_2011_age45-49_female.csv")
  download.file("https://dataverse.harvard.edu/api/access/datafile/2776433", "./nutrition/aux/genus/foodAgeSex/EdibleFood_2011_age45-49_male.csv")
  download.file("https://dataverse.harvard.edu/api/access/datafile/2781795", "./nutrition/aux/genus/foodAgeSex/EdibleFood_2011_age5-9_bothsexes.csv")
  download.file("https://dataverse.harvard.edu/api/access/datafile/2776436", "./nutrition/aux/genus/foodAgeSex/EdibleFood_2011_age50-54_female.csv")
  download.file("https://dataverse.harvard.edu/api/access/datafile/2776437", "./nutrition/aux/genus/foodAgeSex/EdibleFood_2011_age50-54_male.csv")
  download.file("https://dataverse.harvard.edu/api/access/datafile/2776440", "./nutrition/aux/genus/foodAgeSex/EdibleFood_2011_age55-59_female.csv")
  download.file("https://dataverse.harvard.edu/api/access/datafile/2776438", "./nutrition/aux/genus/foodAgeSex/EdibleFood_2011_age55-59_male.csv")
  download.file("https://dataverse.harvard.edu/api/access/datafile/2776443", "./nutrition/aux/genus/foodAgeSex/EdibleFood_2011_age60-64_female.csv")
  download.file("https://dataverse.harvard.edu/api/access/datafile/2776439", "./nutrition/aux/genus/foodAgeSex/EdibleFood_2011_age60-64_male.csv")
  download.file("https://dataverse.harvard.edu/api/access/datafile/2776442", "./nutrition/aux/genus/foodAgeSex/EdibleFood_2011_age65-69_female.csv")
  download.file("https://dataverse.harvard.edu/api/access/datafile/2776441", "./nutrition/aux/genus/foodAgeSex/EdibleFood_2011_age65-69_male.csv")
  download.file("https://dataverse.harvard.edu/api/access/datafile/2776444", "./nutrition/aux/genus/foodAgeSex/EdibleFood_2011_age70-74_female.csv")
  download.file("https://dataverse.harvard.edu/api/access/datafile/2776445", "./nutrition/aux/genus/foodAgeSex/EdibleFood_2011_age70-74_male.csv")
  download.file("https://dataverse.harvard.edu/api/access/datafile/2776446", "./nutrition/aux/genus/foodAgeSex/EdibleFood_2011_age75-79_female.csv")
  download.file("https://dataverse.harvard.edu/api/access/datafile/2776448", "./nutrition/aux/genus/foodAgeSex/EdibleFood_2011_age75-79_male.csv")
  download.file("https://dataverse.harvard.edu/api/access/datafile/2776447", "./nutrition/aux/genus/foodAgeSex/EdibleFood_2011_age80+_female.csv")
  download.file("https://dataverse.harvard.edu/api/access/datafile/2776449", "./nutrition/aux/genus/foodAgeSex/EdibleFood_2011_age80+_male.csv")

#Download age-sex specific nutrient intake files----
download.file("https://dataverse.harvard.edu/api/access/datafile/2781797", "./nutrition/aux/genus/nutAgeSex/NutrientTotal_withFortification_age0-4_bothsexes.csv")
download.file("https://dataverse.harvard.edu/api/access/datafile/2776353", "./nutrition/aux/genus/foodAgeSex/NutrientTotal_withFortification_age10-14_female.csv")
download.file("https://dataverse.harvard.edu/api/access/datafile/2776354", "./nutrition/aux/genus/foodAgeSex/NutrientTotal_withFortification_age10-14_male.csv")
download.file("https://dataverse.harvard.edu/api/access/datafile/2776355", "./nutrition/aux/genus/foodAgeSex/NutrientTotal_withFortification_age15-19_female.csv")
download.file("https://dataverse.harvard.edu/api/access/datafile/2776356", "./nutrition/aux/genus/foodAgeSex/NutrientTotal_withFortification_age15-19_male.csv")
download.file("https://dataverse.harvard.edu/api/access/datafile/2776359", "./nutrition/aux/genus/foodAgeSex/NutrientTotal_withFortification_age20-24_female.csv")
download.file("https://dataverse.harvard.edu/api/access/datafile/2776366", "./nutrition/aux/genus/foodAgeSex/NutrientTotal_withFortification_age20-24_male.csv")
download.file("https://dataverse.harvard.edu/api/access/datafile/2776364", "./nutrition/aux/genus/foodAgeSex/NutrientTotal_withFortification_age25-29_female.csv")
download.file("https://dataverse.harvard.edu/api/access/datafile/2776360", "./nutrition/aux/genus/foodAgeSex/NutrientTotal_withFortification_age25-29_male.csv")
download.file("https://dataverse.harvard.edu/api/access/datafile/2776362", "./nutrition/aux/genus/foodAgeSex/NutrientTotal_withFortification_age30-34_female.csv")
download.file("https://dataverse.harvard.edu/api/access/datafile/2776361", "./nutrition/aux/genus/foodAgeSex/NutrientTotal_withFortification_age30-34_male.csv")
download.file("https://dataverse.harvard.edu/api/access/datafile/2776363", "./nutrition/aux/genus/foodAgeSex/NutrientTotal_withFortification_age35-39_female.csv")
download.file("https://dataverse.harvard.edu/api/access/datafile/2776365", "./nutrition/aux/genus/foodAgeSex/NutrientTotal_withFortification_age35-39_male.csv")
download.file("https://dataverse.harvard.edu/api/access/datafile/2776367", "./nutrition/aux/genus/foodAgeSex/NutrientTotal_withFortification_age40-44_female.csv")
download.file("https://dataverse.harvard.edu/api/access/datafile/2776371", "./nutrition/aux/genus/foodAgeSex/NutrientTotal_withFortification_age40-44_male.csv")
download.file("https://dataverse.harvard.edu/api/access/datafile/2776369", "./nutrition/aux/genus/foodAgeSex/NutrientTotal_withFortification_age45-49_female.csv")
download.file("https://dataverse.harvard.edu/api/access/datafile/2776375", "./nutrition/aux/genus/foodAgeSex/NutrientTotal_withFortification_age45-49_male.csv")
download.file("https://dataverse.harvard.edu/api/access/datafile/2781796", "./nutrition/aux/genus/foodAgeSex/NutrientTotal_withFortification_age5-9_bothsexes.csv")
download.file("https://dataverse.harvard.edu/api/access/datafile/2776370", "./nutrition/aux/genus/foodAgeSex/NutrientTotal_withFortification_age50-54_female.csv")
download.file("https://dataverse.harvard.edu/api/access/datafile/2776368", "./nutrition/aux/genus/foodAgeSex/NutrientTotal_withFortification_age50-54_male.csv")
download.file("https://dataverse.harvard.edu/api/access/datafile/2776372", "./nutrition/aux/genus/foodAgeSex/NutrientTotal_withFortification_age55-59_female.csv")
download.file("https://dataverse.harvard.edu/api/access/datafile/2776373", "./nutrition/aux/genus/foodAgeSex/NutrientTotal_withFortification_age55-59_male.csv")
download.file("https://dataverse.harvard.edu/api/access/datafile/2776374", "./nutrition/aux/genus/foodAgeSex/NutrientTotal_withFortification_age60-64_female.csv")
download.file("https://dataverse.harvard.edu/api/access/datafile/2776377", "./nutrition/aux/genus/foodAgeSex/NutrientTotal_withFortification_age60-64_male.csv")
download.file("https://dataverse.harvard.edu/api/access/datafile/2776379", "./nutrition/aux/genus/foodAgeSex/NutrientTotal_withFortification_age65-69_female.csv")
download.file("https://dataverse.harvard.edu/api/access/datafile/2776378", "./nutrition/aux/genus/foodAgeSex/NutrientTotal_withFortification_age65-69_male.csv")
download.file("https://dataverse.harvard.edu/api/access/datafile/2776376", "./nutrition/aux/genus/foodAgeSex/NutrientTotal_withFortification_age70-74_female.csv")
download.file("https://dataverse.harvard.edu/api/access/datafile/2776384", "./nutrition/aux/genus/foodAgeSex/NutrientTotal_withFortification_age70-74_male.csv")
download.file("https://dataverse.harvard.edu/api/access/datafile/2776383", "./nutrition/aux/genus/foodAgeSex/NutrientTotal_withFortification_age75-79_female.csv")
download.file("https://dataverse.harvard.edu/api/access/datafile/2776380", "./nutrition/aux/genus/foodAgeSex/NutrientTotal_withFortification_age75-79_male.csv")
download.file("https://dataverse.harvard.edu/api/access/datafile/2776381", "./nutrition/aux/genus/foodAgeSex/NutrientTotal_withFortification_age80+_female.csv")
download.file("https://dataverse.harvard.edu/api/access/datafile/2776382", "./nutrition/aux/genus/foodAgeSex/NutrientTotal_withFortification_age80+_male.csv")

# Download nutrient-specific food consumed files
download.file("https://dataverse.harvard.edu/api/access/datafile/2776454", "./nutrition/aux/genus/foodNut/NutrientsByFood_2011_01calories.csv")
download.file("https://dataverse.harvard.edu/api/access/datafile/2776455", "./nutrition/aux/genus/foodNut/NutrientsByFood_2011_02protein.csv")
download.file("https://dataverse.harvard.edu/api/access/datafile/2776452", "./nutrition/aux/genus/foodNut/NutrientsByFood_2011_03fat.csv")
download.file("https://dataverse.harvard.edu/api/access/datafile/2776450", "./nutrition/aux/genus/foodNut/NutrientsByFood_2011_04carbohydrates.csv")
download.file("https://dataverse.harvard.edu/api/access/datafile/2776453", "./nutrition/aux/genus/foodNut/NutrientsByFood_2011_05vitaminC.csv")
download.file("https://dataverse.harvard.edu/api/access/datafile/2776451", "./nutrition/aux/genus/foodNut/NutrientsByFood_2011_06vitaminA.csv")
download.file("https://dataverse.harvard.edu/api/access/datafile/2776456", "./nutrition/aux/genus/foodNut/NutrientsByFood_2011_07folate.csv")
download.file("https://dataverse.harvard.edu/api/access/datafile/2776457", "./nutrition/aux/genus/foodNut/NutrientsByFood_2011_08calcium.csv")
download.file("https://dataverse.harvard.edu/api/access/datafile/2776459", "./nutrition/aux/genus/foodNut/NutrientsByFood_2011_09iron.csv")
download.file("https://dataverse.harvard.edu/api/access/datafile/2776458", "./nutrition/aux/genus/foodNut/NutrientsByFood_2011_10zinc.csv")
download.file("https://dataverse.harvard.edu/api/access/datafile/2776460", "./nutrition/aux/genus/foodNut/NutrientsByFood_2011_11potassium.csv")
download.file("https://dataverse.harvard.edu/api/access/datafile/2776462", "./nutrition/aux/genus/foodNut/NutrientsByFood_2011_12dietaryfiber.csv")
download.file("https://dataverse.harvard.edu/api/access/datafile/2776461", "./nutrition/aux/genus/foodNut/NutrientsByFood_2011_13copper.csv")
download.file("https://dataverse.harvard.edu/api/access/datafile/2776463", "./nutrition/aux/genus/foodNut/NutrientsByFood_2011_14sodium.csv")
download.file("https://dataverse.harvard.edu/api/access/datafile/2776464", "./nutrition/aux/genus/foodNut/NutrientsByFood_2011_15phosphorus.csv")
download.file("https://dataverse.harvard.edu/api/access/datafile/2776466", "./nutrition/aux/genus/foodNut/NutrientsByFood_2011_16thiamin.csv")
download.file("https://dataverse.harvard.edu/api/access/datafile/2776465", "./nutrition/aux/genus/foodNut/NutrientsByFood_2011_17riboflavin.csv")
download.file("https://dataverse.harvard.edu/api/access/datafile/2776467", "./nutrition/aux/genus/foodNut/NutrientsByFood_2011_18niacin.csv")
download.file("https://dataverse.harvard.edu/api/access/datafile/2776468", "./nutrition/aux/genus/foodNut/NutrientsByFood_2011_19vitB6.csv")
download.file("https://dataverse.harvard.edu/api/access/datafile/2776469", "./nutrition/aux/genus/foodNut/NutrientsByFood_2011_21magnesium.csv")
download.file("https://dataverse.harvard.edu/api/access/datafile/2776470", "./nutrition/aux/genus/foodNut/NutrientsByFood_2011_23saturatedFA.csv")
download.file("https://dataverse.harvard.edu/api/access/datafile/2776471", "./nutrition/aux/genus/foodNut/NutrientsByFood_2011_24monounsatFA.csv")
download.file("https://dataverse.harvard.edu/api/access/datafile/2776472", "./nutrition/aux/genus/foodNut/NutrientsByFood_2011_25polyunsatFA.csv")



